-- Deprecated historical SQL snapshot. Do not execute this file.
-- The single operational implementation of public.create_transaction_atomic
-- is defined by the migration chain, ending at:
--   supabase/migrations/20260927000001_converge_transaction_atomic_security.sql
-- That migration also provides the secure 17-argument compatibility wrapper.
-- Apply migrations through the approved, isolated Supabase workflow only.
